//! Deterministic rendering of generated docs from the code (the source of truth).
//!
//! Everything here is a pure function of the repository contents — the published
//! constants/tables in `chrony-rs-core` and a couple of filesystem scans. No
//! timestamps, no environment, so output is byte-stable and the freshness gate is
//! a clean diff.

use std::path::Path;

use chrony_rs_core::config;
use chrony_rs_core::{TARGET_CHRONY_VERSION, TRACE_SCHEMA};

const HEADER: &str = "\
<!-- DO NOT EDIT BY HAND.
Generated by `cargo xtask gen` from chrony-rs-core constants and repository scans.
Run `cargo xtask check` to verify freshness; the pre-commit hook enforces it. -->
";

/// Render `docs/generated/status.md`.
pub fn status_md(root: &Path) -> String {
    let mut s = String::new();
    s.push_str(HEADER);
    s.push_str("\n# chrony-rs generated status\n\n");
    s.push_str("Machine facts rendered from the code so they cannot drift from it.\n\n");

    s.push_str("## Declared targets\n\n");
    s.push_str(&format!("- Target chrony oracle version: `{TARGET_CHRONY_VERSION}`\n"));
    s.push_str(&format!("- Trace schema: `{TRACE_SCHEMA}`\n"));
    s.push_str(&format!("- `unsafe` blocks in `crates/*/src`: {}\n\n", count_unsafe(root)));

    let dirs = config::known_directives();
    s.push_str(&format!(
        "## Recognized config directives ({}, oracle-anchored to chrony {})\n\n",
        dirs.len(),
        TARGET_CHRONY_VERSION
    ));
    s.push_str(&render_word_grid(dirs));
    s.push('\n');

    let flags = config::source_flag_options();
    s.push_str(&format!("## Source flag options ({})\n\n", flags.len()));
    s.push_str(&render_word_grid(flags));
    s.push('\n');

    let values = config::source_value_options();
    s.push_str(&format!("## Source value options ({})\n\n", values.len()));
    s.push_str(&render_word_grid(values));
    s.push('\n');

    s.push_str("## Oracle config fixtures\n\n");
    s.push_str(&render_fixture_list(root));

    s
}

/// Render a sorted list of words as a wrapped, code-formatted block (6 per line),
/// independent of input order so reordering the source array does not churn docs.
fn render_word_grid(words: &[&str]) -> String {
    let mut sorted: Vec<&str> = words.to_vec();
    sorted.sort_unstable();
    let mut out = String::new();
    for (i, w) in sorted.iter().enumerate() {
        out.push('`');
        out.push_str(w);
        out.push('`');
        if i + 1 < sorted.len() {
            out.push_str(if (i + 1) % 6 == 0 { ",\n" } else { ", " });
        }
    }
    out.push('\n');
    out
}

/// List the oracle config fixtures (sorted), so the inventory in the docs always
/// matches what is on disk.
fn render_fixture_list(root: &Path) -> String {
    let dir = root.join("tools/oracle/config-fixtures");
    let mut names: Vec<String> = std::fs::read_dir(&dir)
        .map(|rd| {
            rd.filter_map(|e| e.ok())
                .filter_map(|e| e.file_name().into_string().ok())
                .filter(|n| n.ends_with(".conf"))
                .collect()
        })
        .unwrap_or_default();
    names.sort();
    if names.is_empty() {
        return "_(none found)_\n".to_string();
    }
    let mut out = format!("{} fixtures:\n\n", names.len());
    for n in names {
        out.push_str(&format!("- `{n}`\n"));
    }
    out
}

/// Count `unsafe` occurrences across crate sources. A scan, not a parse: any
/// occurrence (even in a comment) counts, which is the conservative direction —
/// it can only over-report, never hide an `unsafe` block.
pub fn count_unsafe(root: &Path) -> usize {
    let crates = root.join("crates");
    let mut count = 0;
    visit_rs_files(&crates, &mut |content| {
        count += content.matches("unsafe").count();
    });
    // xtask itself and tools are excluded by construction (only crates/ scanned).
    count
}

fn visit_rs_files(dir: &Path, f: &mut impl FnMut(&str)) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.filter_map(|e| e.ok()) {
        let path = entry.path();
        if path.is_dir() {
            visit_rs_files(&path, f);
        } else if path.extension().map(|e| e == "rs").unwrap_or(false) {
            if let Ok(content) = std::fs::read_to_string(&path) {
                f(&content);
            }
        }
    }
}
