//! Deterministic rendering of generated docs from the code (the source of truth).
//!
//! Everything here is a pure function of the repository contents — the published
//! constants/tables in `chrony-rs-core` and a couple of filesystem scans. No
//! timestamps, no environment, so output is byte-stable and the freshness gate is
//! a clean diff.

use std::path::Path;

use chrony_rs_core::config;
use chrony_rs_core::{TARGET_CHRONY_VERSION, TRACE_SCHEMA};

const HEADER: &str = "\
<!-- DO NOT EDIT BY HAND.
Generated by `cargo xtask gen` from chrony-rs-core constants and repository scans.
Run `cargo xtask check` to verify freshness; the pre-commit hook enforces it. -->
";

/// Render `docs/generated/status.md`.
pub fn status_md(root: &Path) -> String {
    let mut s = String::new();
    s.push_str(HEADER);
    s.push_str("\n# chrony-rs generated status\n\n");
    s.push_str("Machine facts rendered from the code so they cannot drift from it.\n\n");

    s.push_str("## Declared targets\n\n");
    s.push_str(&format!("- Target chrony oracle version: `{TARGET_CHRONY_VERSION}`\n"));
    s.push_str(&format!("- Trace schema: `{TRACE_SCHEMA}`\n"));
    s.push_str(&format!("- `unsafe` blocks in `crates/*/src`: {}\n\n", count_unsafe(root)));

    let dirs = config::known_directives();
    s.push_str(&format!(
        "## Recognized config directives ({}, oracle-anchored to chrony {})\n\n",
        dirs.len(),
        TARGET_CHRONY_VERSION
    ));
    s.push_str(&render_word_grid(dirs));
    s.push('\n');

    let flags = config::source_flag_options();
    s.push_str(&format!("## Source flag options ({})\n\n", flags.len()));
    s.push_str(&render_word_grid(flags));
    s.push('\n');

    let values = config::source_value_options();
    s.push_str(&format!("## Source value options ({})\n\n", values.len()));
    s.push_str(&render_word_grid(values));
    s.push('\n');

    s.push_str("## Oracle config fixtures\n\n");
    s.push_str(&render_fixture_list(root));

    s
}

/// Render a sorted list of words as a wrapped, code-formatted block (6 per line),
/// independent of input order so reordering the source array does not churn docs.
fn render_word_grid(words: &[&str]) -> String {
    let mut sorted: Vec<&str> = words.to_vec();
    sorted.sort_unstable();
    let mut out = String::new();
    for (i, w) in sorted.iter().enumerate() {
        out.push('`');
        out.push_str(w);
        out.push('`');
        if i + 1 < sorted.len() {
            out.push_str(if (i + 1) % 6 == 0 { ",\n" } else { ", " });
        }
    }
    out.push('\n');
    out
}

/// List the oracle config fixtures (sorted), so the inventory in the docs always
/// matches what is on disk.
fn render_fixture_list(root: &Path) -> String {
    let dir = root.join("tools/oracle/config-fixtures");
    let mut names: Vec<String> = std::fs::read_dir(&dir)
        .map(|rd| {
            rd.filter_map(|e| e.ok())
                .filter_map(|e| e.file_name().into_string().ok())
                .filter(|n| n.ends_with(".conf"))
                .collect()
        })
        .unwrap_or_default();
    names.sort();
    if names.is_empty() {
        return "_(none found)_\n".to_string();
    }
    let mut out = format!("{} fixtures:\n\n", names.len());
    for n in names {
        out.push_str(&format!("- `{n}`\n"));
    }
    out
}

/// Render `docs/negative-capabilities.md`.
///
/// The ledger is **generated** so it cannot drift from the code: the list of
/// modules that *do* exist comes straight from the parity [`MAP`](crate::parity)
/// (Full + Partial), and the `unsafe` count is the live scan. The curated prose
/// below states only what is genuinely *not* admitted as daemon behavior — and
/// because the "implemented" list is machine-derived, prose can never again claim
/// an implemented module is absent without the freshness gate rejecting it.
pub fn negative_capabilities_md(root: &Path) -> String {
    let mut s = String::new();
    s.push_str(HEADER);
    s.push_str(
        "\n# Negative capabilities\n\n\
        The things `chrony-rs` deliberately does **not** do yet. Each entry is a \
        promise that the absence is intentional and fails *closed* (errors or is \
        simply absent), never silently approximated.\n\n\
        This file is **generated** (`cargo xtask gen`) and freshness-gated: the \
        list of modules that *do* exist is derived from the port-parity matrix, so \
        it cannot contradict what has actually been ported. Removing something from \
        the \"not yet admitted\" lists below requires the corresponding court and \
        evidence to exist first.\n\n",
    );

    // --- Generated: modules that exist offline, derived from the parity MAP. ---
    s.push_str(
        "## Implemented as isolated, court-backed modules (offline — NOT daemon-admitted)\n\n\
        These chrony translation units have real, court-backed counterparts in \
        `chrony-rs-core`, exercised by unit/differential tests **in isolation**. \
        They are *not* wired into a running discipline loop and their behavior is \
        *not* yet compared end-to-end against a live `chronyd`. Presence here is a \
        statement about ported algorithms, not about daemon behavior. See the \
        [port-parity matrix](generated/port-parity.md) for per-function detail and \
        the courts behind each.\n\n",
    );
    for m in crate::parity::ported_modules() {
        let tag = if m.full { "full" } else { "partial" };
        s.push_str(&format!("- `{}` — {} _(port: {})_\n", m.c, m.role, tag));
    }
    s.push('\n');

    // --- Curated: what is genuinely not admitted yet. ---
    s.push_str(NEGATIVE_CLAIMS);

    // --- Generated: the unsafe ledger. ---
    s.push_str(&format!(
        "## Unsafe\n\n\
        - **No `unsafe` code.** The current count is {}\u{a0}(see \
        `security-boundary.md`). This is recorded even though it is zero, so a \
        future addition is conspicuous and gated.\n",
        count_unsafe(root)
    ));

    s
}

/// Curated negative claims: behavior genuinely **not** admitted yet. These are the
/// statements the doctrine forbids overclaiming on; the "implemented" list above is
/// generated separately so the two halves cannot contradict each other.
const NEGATIVE_CLAIMS: &str = "\
## Not yet admitted as daemon behavior

The modules above exist in isolation. The *integration* that would make them a
daemon does not, and is not claimed:

- **No live poll T1/T4 capture.** The daemon-side recording of our transmit (T1)
  and receive (T4) timestamps for a live poll/response is not wired up, so the
  measurement stage is not fed by real exchanges.
- **No source-selection oracle replay.** Selection runs on *computed* offsets in
  an integration test only; it is not driven from a captured `chronyd` trace nor
  compared against the daemon's chosen source.
- **No full discipline state machine.** The offset/frequency/skew/step/slew
  *algorithms* exist as modules (`local`, `sys_null`, `smooth`, `tempcomp`,
  `sourcestats`, `regress`), but the closed loop that drives a clock from live
  measurements is not assembled or admitted.
- **No end-to-end chronyd parity.** No court asserts that a full poll→select→
  discipline→report cycle matches real `chronyd` over a captured trace.
- **No drift/dump/state file *daemon I/O*.** `sourcestats` can serialize/restore
  its sample register (tested), but the daemon-level drift/dump/state file
  lifecycle (paths, atomic writes, load-on-start) is not wired up.

## Daemon / clock

- **No real system-clock mutation.** No `step`/`slew` of a live clock exists; the
  ported discipline math returns corrections instead of applying them.
- **No `--lab-daemon` mode.** Deferred behind explicit lab guards.
- **No NTP server/responder.** Client-shaped packet handling only; the
  `clientlog` rate limiter is ported in isolation but no socket serves time.

## Control

- **No live control-socket transport.** `chronyc-rs tracking|sources|sourcestats|
  activity|serverstats` against a running daemon is not implemented; the binary
  exits non-zero with an explanation. Only offline rendering works.
- **No control protocol encode/decode.** The Unix/UDP control wire format is not
  yet modeled (the `pktlength` length tables are ported, but not the transport).

## NTP wire

- **No authentication (MAC/key-id) verification.** Bytes are preserved, not
  checked (MD5 is ported and vectored, but not wired into packet verification).
- **No NTS.** No handshake, cookies, records, or key material.
- **Extension fields framed, not interpreted.** `ntp_ext` parses/formats the TLV
  framing, but the semantics of specific extension fields are not acted on.

## Config

- **Recognized \u{2260} modeled.** All 93 chrony 4.5 directives are *recognized*
  and `server`/`pool`/`peer` *options* are validated 1:1, but only a subset of
  directives is given typed *semantics*. Unmodeled directives are preserved, not
  executed.
- **No `include`/`confdir` expansion.** Recognized as keywords, not followed.
- **No exact diagnostic-text parity** beyond what `config-atlas.md` admits.

## Replay

- **Replay executes, but applies no chrony policy.** `--replay` drives a validated
  trace through a deterministic simulated clock and emits a reproducible
  decision-log hash; it does not implement chrony's selection/filtering/discipline,
  and the `selected_source` it reports is a transparent placeholder.
- **No oracle comparison.** Expectation checking is the runner's own decision-log
  hash (self-consistency), never an assertion of parity with real `chronyd`.

## OS / platform

- **No OS clock adapters.** No `adjtimex`/`clock_adjtime`/BSD/macOS/illumos code.
- **No privilege/capability handling, chroot, or sandbox.**
- **No refclock or RTC hardware support.**

";

/// Render `crates/chrony-rs-core/README.md`.
///
/// Generated so the crate's headline (which chrony translation units it ports, the
/// `unsafe` count, the target version) cannot drift from the code: the lists come
/// from the parity [`MAP`](crate::parity) and the live scans.
pub fn core_readme(root: &Path) -> String {
    let modules = crate::parity::ported_modules();
    let full: Vec<_> = modules.iter().filter(|m| m.full).collect();
    let partial: Vec<_> = modules.iter().filter(|m| !m.full).collect();
    let unsafe_count = count_unsafe(root);

    let mut s = String::new();
    s.push_str(HEADER);
    s.push_str(&format!(
        "\n# chrony-rs-core\n\n\
        The deterministic time-discipline **brain** of [chrony-rs](../../README.md): a\n\
        forensic reconstruction of chrony {TARGET_CHRONY_VERSION}'s internals that runs \
        *without* a host\n\
        clock, sockets, or privileges (the one documented exception is synchronous DNS in\n\
        `nameserv`). Everything that touches the host is injected behind a trait or closure\n\
        so the logic is testable against the real C and against protocol/spec oracles.\n\n\
        This file is **generated** (`cargo xtask gen`) and freshness-gated — the lists\n\
        below come from the port-parity matrix, so they cannot disagree with what is\n\
        actually ported. See the [full matrix](../../docs/generated/port-parity.md) and the\n\
        [per-function gap view](../../docs/generated/port-parity-functions.md).\n\n"
    ));

    s.push_str(&format!(
        "## Fully ported chrony translation units ({})\n\n\
        Every function in these units has a court-backed counterpart (differential tests\n\
        against the real compiled C and/or protocol-spec vectors):\n\n",
        full.len()
    ));
    for m in &full {
        s.push_str(&format!("- `{}` → {} — {}\n", m.c, fmt_rust(m.rust), m.role));
    }

    s.push_str(&format!(
        "\n## Partially ported ({})\n\n\
        Behavior ported with at least one executable court, but not every function (see the\n\
        matrix for the exact gap):\n\n",
        partial.len()
    ));
    for m in &partial {
        s.push_str(&format!("- `{}` → {} — {}\n", m.c, fmt_rust(m.rust), m.role));
    }

    s.push_str(&format!(
        "\n## Invariants\n\n\
        - **`unsafe` blocks:** {unsafe_count} (scanned across `crates/*/src`).\n\
        - **Target chrony oracle:** {TARGET_CHRONY_VERSION}.\n\
        - **Trace schema:** `{TRACE_SCHEMA}`.\n\n\
        Host mutation (clock, sockets, privileges) lives in the binary crates behind narrow\n\
        boundaries; see [`chronyd-rs`](../chronyd-rs/README.md) and\n\
        [`chronyc-rs`](../chronyc-rs/README.md).\n"
    ));
    s
}

/// Render `crates/chronyd-rs/README.md`.
pub fn chronyd_readme(_root: &Path) -> String {
    let mut s = String::new();
    s.push_str(HEADER);
    s.push_str(&format!(
        "\n# chronyd-rs\n\n\
        The daemon / replay binary of [chrony-rs](../../README.md). It hosts the\n\
        [`chrony-rs-core`](../chrony-rs-core/README.md) brain in **lab and offline modes\n\
        only** — it does not discipline a real system clock or open production sockets.\n\n\
        This file is **generated** (`cargo xtask gen`) and freshness-gated.\n\n\
        ## What it does\n\n\
        - `chronyd-rs --check-config <file>` — parse and validate a chrony config the way\n\
        chrony {TARGET_CHRONY_VERSION} does (acceptance + diagnostics oracle-witnessed; see\n\
        [`docs/config-atlas.md`](../../docs/config-atlas.md)).\n\
        - `chronyd-rs --replay <trace.json>` — drive a validated deterministic trace\n\
        through a simulated clock and emit a reproducible decision-log hash.\n\n\
        ## What it deliberately does NOT do\n\n\
        No real clock step/slew, no NTP serving, no live control socket — the boundaries\n\
        are enumerated in [`docs/negative-capabilities.md`](../../docs/negative-capabilities.md)\n\
        (itself generated). Targets chrony {TARGET_CHRONY_VERSION}.\n"
    ));
    s
}

/// Render `crates/chronyc-rs/README.md`.
pub fn chronyc_readme(_root: &Path) -> String {
    let mut s = String::new();
    s.push_str(HEADER);
    s.push_str(&format!(
        "\n# chronyc-rs\n\n\
        The control-client / output-parity tool of [chrony-rs](../../README.md). It renders\n\
        the exact textual reports `chronyc` prints, so chrony-rs output can be checked\n\
        byte-for-byte against chrony {TARGET_CHRONY_VERSION}.\n\n\
        This file is **generated** (`cargo xtask gen`) and freshness-gated.\n\n\
        ## What it does\n\n\
        - Offline rendering of `tracking` / `sources` / `sourcestats` / `activity` /\n\
        `serverstats` reports from a JSON fixture, with layouts live-witnessed against\n\
        chrony {TARGET_CHRONY_VERSION} (see [`docs/chronyc-parity.md`](../../docs/chronyc-parity.md)).\n\n\
        ## What it deliberately does NOT do\n\n\
        No live control-socket transport to a running daemon (the wire protocol is not yet\n\
        modeled); it renders from fixtures only. See\n\
        [`docs/negative-capabilities.md`](../../docs/negative-capabilities.md). Targets\n\
        chrony {TARGET_CHRONY_VERSION}.\n"
    ));
    s
}

/// Format a module's Rust paths as `` `a`, `b` `` (or `—` if none).
fn fmt_rust(rust: &[&str]) -> String {
    if rust.is_empty() {
        "—".to_string()
    } else {
        rust.iter().map(|r| format!("`{r}`")).collect::<Vec<_>>().join(", ")
    }
}

/// Count `unsafe` occurrences across crate sources. A scan, not a parse: any
/// occurrence (even in a comment) counts, which is the conservative direction —
/// it can only over-report, never hide an `unsafe` block.
pub fn count_unsafe(root: &Path) -> usize {
    let crates = root.join("crates");
    let mut count = 0;
    visit_rs_files(&crates, &mut |content| {
        count += content.matches("unsafe").count();
    });
    // xtask itself and tools are excluded by construction (only crates/ scanned).
    count
}

fn visit_rs_files(dir: &Path, f: &mut impl FnMut(&str)) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.filter_map(|e| e.ok()) {
        let path = entry.path();
        if path.is_dir() {
            visit_rs_files(&path, f);
        } else if path.extension().map(|e| e == "rs").unwrap_or(false) {
            if let Ok(content) = std::fs::read_to_string(&path) {
                f(&content);
            }
        }
    }
}
